# Generated by Django 3.2 on 2022-02-19 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='phone must be an egyptian phone number...', regex='^01[1|0|2|5][0-9]{8}$')])),
                ('email', models.EmailField(max_length=50)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='uploads/')),
                ('password', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(blank=True, default=None, null=True)),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('facebook_profile', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
    ]
