# Generated by Django 2.2 on 2022-02-14 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20220214_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_data',
            name='cover',
        ),
    ]
