# Generated by Django 2.2 on 2022-02-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20220214_1512'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='project_data',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='project_data',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
