# Generated by Django 2.2 on 2022-02-16 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_data_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_comments',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.Project_data'),
        ),
    ]
