# Generated by Django 2.2 on 2022-02-16 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_data_remain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate_project',
            name='amount',
        ),
    ]
