# Generated by Django 2.2 on 2022-02-16 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_donate_project_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate_project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donate', to='users.Users'),
        ),
    ]
