# Generated by Django 2.2 on 2022-02-16 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20220216_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate_project',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donate', to='projects.Project_data'),
        ),
    ]
