# Generated by Django 2.2 on 2022-02-16 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20220216_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate_project',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pproject', to='projects.Project_data'),
        ),
        migrations.AlterField(
            model_name='report_project',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.Project_data'),
        ),
    ]
