# Generated by Django 2.2 on 2022-02-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20220216_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_data',
            name='current_money',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
