# Generated by Django 2.2 on 2022-02-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20220218_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate_project',
            name='value',
            field=models.FloatField(),
        ),
    ]
