# Generated by Django 2.2 on 2022-02-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20220218_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate_project',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rate_project',
            name='value',
            field=models.FloatField(),
        ),
    ]
