# Generated by Django 2.2 on 2022-02-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20220218_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate_project',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
