# Generated by Django 2.2 on 2022-02-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20220218_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate_project',
            name='value',
            field=models.IntegerField(),
        ),
    ]
